name: Tabular CDC Bootstrapper PR Unit Testing

on:
  pull_request:
    branches: 
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pipenv
          cd tabular-cdc-bootstrapper
          pipenv install --dev

      - name: Run tests
        run: |
          cd tabular-cdc-bootstrapper
          pipenv run pytest
