name: Tabular CDC Bootstrapper PR Unit Testing

on:
  pull_request:
    branches: 
      - main

env:
  S3_BUCKET_TO_MONITOR:        ${{ vars.S3_BUCKET_TO_MONITOR }} 
  S3_PATH_TO_MONITOR:          ${{ vars.S3_PATH_TO_MONITOR }}

  TABULAR_CREDENTIAL:          ${{ secrets.TABULAR_CREDENTIAL }}
  TABULAR_TARGET_WAREHOUSE:    ${{ vars.TABULAR_TARGET_WAREHOUSE }}
  TABULAR_CATALOG_URI:         ${{ vars.TABULAR_CATALOG_URI }}
  TABULAR_CDC_ID_FIELD:        ${{ vars.TABULAR_CDC_ID_FIELD }}
  TABULAR_CDC_TIMESTAMP_FIELD: ${{ vars.TABULAR_CDC_TIMESTAMP_FIELD }}

jobs:
  build_and_test_batch:
    name: Build dockerfile and execute pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run make test
        run: |
          cd batch-bootstrapper
          env | grep -E '^TABULAR_|^S3_' > .env # gather gh actions vars for docker test run
          echo "running with the following configs..."
          grep -v '^TABULAR_CREDENTIAL' .env
          make test
